<#
.SYNOPSIS
    Package the contents of dist/ into a zip plus a shareable end-user
    PowerShell installer, both written to Ladruno_files/.

.DESCRIPTION
    Run this AFTER `Ladruno_scripts\build.bat` has produced dist/. The
    output is a pair of files in Ladruno_files/:
        Ladruno_OpenSees_setup.zip  - the binaries (zip of dist/)
        install.ps1                 - the script users run on their machine

    Distribute both files together. Receivers run install.ps1 (right-click
    > Run with PowerShell, or `powershell -ExecutionPolicy Bypass -File
    install.ps1`). The installer shows the LADRUNO ASCII banner, asks for
    an install location, expands the zip there, and optionally adds the
    bin folder to user PATH.

.PARAMETER Version
    Optional version string baked into the zip filename. Default: today's
    date in YYYYMMDD format.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File Ladruno_scripts\make_installer.ps1
    powershell -ExecutionPolicy Bypass -File Ladruno_scripts\make_installer.ps1 -Version 2026.05
#>
param(
    [string]$Version  = (Get-Date -Format "yyyyMMdd"),
    [switch]$NoExe                                            # skip the .exe wrap step
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$scriptDir = $PSScriptRoot
$root      = Split-Path -Parent $scriptDir
$dist      = Join-Path $root "dist"
$out       = Join-Path $root "Ladruno_files"
$bannerTxt = Join-Path $scriptDir "banner_ASCII.txt"

Write-Host "Ladruno OpenSees - installer packager" -ForegroundColor Cyan
Write-Host "  source : $dist"
Write-Host "  output : $out"
Write-Host ""

if (-not (Test-Path $dist)) {
    Write-Error "dist/ not found at $dist. Run Ladruno_scripts\build.bat first."
    exit 1
}
if (-not (Test-Path $bannerTxt)) {
    Write-Error "banner_ASCII.txt not found at $bannerTxt"
    exit 1
}
if (-not (Test-Path $out)) {
    New-Item -ItemType Directory -Path $out | Out-Null
}

# ---------- 1. zip dist ---------------------------------------------------
$zipName = "Ladruno_OpenSees_$Version.zip"
$zipPath = Join-Path $out $zipName
if (Test-Path $zipPath) { Remove-Item $zipPath }
Write-Host "Compressing dist/ -> $zipName ..." -NoNewline
Compress-Archive -Path "$dist\*" -DestinationPath $zipPath -CompressionLevel Optimal
$mb = [math]::Round((Get-Item $zipPath).Length / 1MB, 1)
Write-Host " done ($mb MB)"

# ---------- 2. read banner text -------------------------------------------
# Read as raw UTF-8 string so the box-drawing glyphs survive the round-trip
# into the generated installer.
$banner = [System.IO.File]::ReadAllText($bannerTxt, [System.Text.Encoding]::UTF8)

# ---------- 3. emit install.ps1 -------------------------------------------
$installerPath = Join-Path $out "install.ps1"

# Use a here-string to build the installer. Backticks are PowerShell escape
# characters; we use them sparingly so the generated script can stand on its own.
$installerContent = @"
<#
.SYNOPSIS
    Ladruno OpenSees end-user installer.
.DESCRIPTION
    Auto-generated by make_installer.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm").
    Distribute alongside Ladruno_OpenSees_$Version.zip.

    Interactive (right-click > Run with PowerShell, or double-click install.exe):
        the script prompts for every choice.

    Scripted / silent (CI, group rollouts):
        powershell -ExecutionPolicy Bypass -File install.ps1 ``
            -InstallPath C:\Tools\Ladruno -VenvPath C:\Tools\Ladruno\venv ``
            -AddToPath -Yes

.PARAMETER InstallPath
    Where to extract the binaries. Default: %LOCALAPPDATA%\Ladruno\OpenSees
.PARAMETER VenvPath
    If given, wire OpenSeesPy into this Python venv (creates it if missing,
    using -BasePython). If omitted, no venv wiring is done.
.PARAMETER BasePython
    Python interpreter used to bootstrap the venv when it doesn't exist.
    Must be Python 3.11. Default: 'python' on PATH.
.PARAMETER AddToPath
    Add <InstallPath>\bin to the user PATH.
.PARAMETER Yes
    Don't prompt before overwriting an existing install dir.
#>
param(
    [string]`$InstallPath,
    [string]`$VenvPath,
    [string]`$BasePython = 'python',
    [switch]`$AddToPath,
    [switch]`$Yes
)
`$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# ---------- splash banner --------------------------------------------------
Write-Host @'
$banner
'@ -ForegroundColor Cyan

Write-Host ""
Write-Host "         Ladruno OpenSees - Installer ($Version)"            -ForegroundColor Yellow
Write-Host "         ----------------------------------------"             -ForegroundColor DarkGray
Write-Host ""
Write-Host "         Includes: OpenSees.exe, OpenSeesSP.exe, OpenSeesMP.exe,"
Write-Host "                   opensees.pyd (Python module), HDF5 + MPCO,"
Write-Host "                   MUMPS sparse solver."
Write-Host ""

# ---------- locate the zip alongside this script / .exe --------------------
# `$PSScriptRoot is empty when this script has been compiled to an .exe by
# ps2exe. Fall back to the executing assembly's location in that case.
if (`$PSScriptRoot) {
    `$here = `$PSScriptRoot
} elseif (`$PSCommandPath) {
    `$here = Split-Path -Parent `$PSCommandPath
} else {
    `$here = [System.IO.Path]::GetDirectoryName([System.Reflection.Assembly]::GetEntryAssembly().Location)
}
`$zipFile = Join-Path `$here "Ladruno_OpenSees_$Version.zip"
if (-not (Test-Path `$zipFile)) {
    Write-Error "Ladruno_OpenSees_$Version.zip not found next to install.exe / install.ps1 at: `$here"
    exit 1
}

# ---------- choose install location ---------------------------------------
`$defaultInstall = Join-Path `$env:LOCALAPPDATA "Ladruno\OpenSees"
if (-not [string]::IsNullOrWhiteSpace(`$InstallPath)) {
    `$installDir = `$InstallPath
} else {
    Write-Host "Install location [default: `$defaultInstall]:" -NoNewline
    `$reply = Read-Host
    if ([string]::IsNullOrWhiteSpace(`$reply)) { `$installDir = `$defaultInstall } else { `$installDir = `$reply }
}

if (Test-Path `$installDir) {
    if (`$Yes) {
        Write-Host "Overwriting existing `$installDir (-Yes)" -ForegroundColor Yellow
    } else {
        Write-Host ""
        Write-Host "WARNING: `$installDir already exists." -ForegroundColor Yellow
        `$overwrite = Read-Host "Overwrite? (y/N)"
        if (`$overwrite -ne 'y') { Write-Host "Aborted."; exit 0 }
    }
    Remove-Item -Recurse -Force `$installDir
}

Write-Host ""
Write-Host "Installing to: `$installDir"
New-Item -ItemType Directory -Path `$installDir -Force | Out-Null
Expand-Archive -Path `$zipFile -DestinationPath `$installDir -Force

`$binDir = Join-Path `$installDir 'bin'
Write-Host "Done. Binaries: `$binDir" -ForegroundColor Green
Write-Host ""

# ---------- add to PATH ----------------------------------------------------
`$doAddPath = `$AddToPath
if (-not `$AddToPath) {
    `$reply = Read-Host "Add `$binDir to your user PATH? (y/N)"
    `$doAddPath = (`$reply -eq 'y')
}
if (`$doAddPath) {
    `$current = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not `$current) { `$current = '' }
    if (`$current -notlike "*`$binDir*") {
        [Environment]::SetEnvironmentVariable('Path', "`$binDir;`$current", 'User')
        Write-Host "Added. Open a new shell to pick up the change." -ForegroundColor Green
    } else {
        Write-Host "`$binDir is already on PATH."
    }
}

# ---------- wire OpenSeesPy into a Python venv -----------------------------
`$venvTarget = `$null
if (-not [string]::IsNullOrWhiteSpace(`$VenvPath)) {
    `$venvTarget = `$VenvPath                      # provided by parameter
} else {
    Write-Host ""
    `$reply = Read-Host "Wire OpenSeesPy into a Python virtualenv? (y/N)"
    if (`$reply -eq 'y') {
        `$defaultVenv = Join-Path `$installDir 'opensees_venv'
        Write-Host ""
        Write-Host "Venv path:" -ForegroundColor Cyan
        Write-Host "  - leave blank to create a new venv at: `$defaultVenv"
        Write-Host "  - or paste the absolute path to an existing venv directory"
        `$venvReply = Read-Host "Venv path"
        if ([string]::IsNullOrWhiteSpace(`$venvReply)) { `$venvTarget = `$defaultVenv } else { `$venvTarget = `$venvReply }
    }
}

if (`$venvTarget) {
    `$venvPython = Join-Path `$venvTarget 'Scripts\python.exe'
    if (-not (Test-Path `$venvPython)) {
        Write-Host "Creating venv at `$venvTarget (base: `$BasePython) ..."
        & `$BasePython -m venv `$venvTarget
        if (`$LASTEXITCODE -ne 0) {
            Write-Warning "venv creation failed. Skipping venv wiring; you can re-run this step manually."
        }
    }
    if (Test-Path `$venvPython) {
        `$pyVer = & `$venvPython -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
        if (`$pyVer -ne '3.11') {
            Write-Warning "Selected venv is Python `$pyVer; opensees.pyd was built for 3.11."
            Write-Warning "It will fail to import. Recreate the venv with Python 3.11."
        }
        `$sitePackages = & `$venvPython -c "import sysconfig; print(sysconfig.get_paths()['purelib'])"
        `$pthFile = Join-Path `$sitePackages 'ladruno_opensees.pth'
        Set-Content -Path `$pthFile -Value `$binDir -Encoding ASCII
        Write-Host "Wired:" -ForegroundColor Green
        Write-Host "  venv: `$venvTarget"
        Write-Host "  .pth: `$pthFile  ->  `$binDir"
        Write-Host ""
        Write-Host "Activate the venv:"
        Write-Host "  cmd:        `$venvTarget\Scripts\activate.bat"
        Write-Host "  powershell: & '`$venvTarget\Scripts\Activate.ps1'"
    }
}

# ---------- usage hint -----------------------------------------------------
Write-Host ""
Write-Host "Try it:" -ForegroundColor Cyan
Write-Host "  & '`$binDir\OpenSees.exe' your_model.tcl"
Write-Host "  python -c ""import sys; sys.path.insert(0, r'`$binDir'); import opensees as ops; print('ok')"""
Write-Host ""
Write-Host "OpenSeesSP / OpenSeesMP need Intel MPI's mpiexec on PATH"  -ForegroundColor DarkGray
Write-Host "(Intel oneAPI install required separately, then call its setvars.bat)" -ForegroundColor DarkGray
Write-Host ""
"@

[System.IO.File]::WriteAllText($installerPath, $installerContent, [System.Text.Encoding]::UTF8)
Write-Host "Wrote installer: $installerPath"

# ---------- 4. compile install.ps1 -> install.exe via PS2EXE ---------------
if (-not $NoExe) {
    if (-not (Get-Module -ListAvailable -Name ps2exe)) {
        Write-Warning "ps2exe module not installed. Install with:"
        Write-Warning "    Install-Module -Name ps2exe -Scope CurrentUser"
        Write-Warning "Skipping .exe build (re-run without -NoExe after install)."
    } else {
        Import-Module ps2exe -Force
        $exePath = Join-Path $out "install.exe"
        if (Test-Path $exePath) { Remove-Item $exePath }
        Write-Host "Compiling install.ps1 -> install.exe via PS2EXE ..." -NoNewline
        # PE/.NET version must fit major.minor.build.revision (each <= 65535).
        # Map a YYYYMMDD date string into "1.0.YYYY.MMDD"; otherwise use as-is.
        if ($Version -match '^\d{8}$') {
            $assemblyVersion = "1.0.$($Version.Substring(0,4)).$($Version.Substring(4,4))"
        } else {
            $assemblyVersion = $Version
        }
        Invoke-PS2EXE `
            -inputFile    $installerPath `
            -outputFile   $exePath `
            -title        "Ladruno OpenSees Installer" `
            -description  "Ladruno OpenSees ($Version) - installer with venv wiring" `
            -company      "Ladruno" `
            -product      "Ladruno OpenSees" `
            -version      $assemblyVersion `
            -noConsole:$false `
            -requireAdmin:$false 2>&1 | Out-Null
        if (Test-Path $exePath) {
            $exeKB = [math]::Round((Get-Item $exePath).Length / 1KB, 0)
            Write-Host " done ($exeKB KB)" -ForegroundColor Green
        } else {
            Write-Warning "install.exe was not produced. Check ps2exe output above."
        }
    }
}

# ---------- summary --------------------------------------------------------
Write-Host ""
Write-Host "Distribute these two files together:" -ForegroundColor Yellow
Get-ChildItem $out -File | Where-Object { $_.Name -match '^(install\.(ps1|exe)|Ladruno_OpenSees_.*\.zip)$' } |
    Select-Object Name, @{n="MB";e={[math]::Round($_.Length/1MB,2)}}, LastWriteTime |
    Format-Table -AutoSize
