"""Wire a venv so BOTH `import opensees` and `import openseesmp` work.

Invoked by installer.iss at install time:
    <venv>\\Scripts\\python.exe wire_venv_pth.py <bin-dir> [<openseesmp-dir>]

  <bin-dir>         {app}\\bin         - opensees.pyd (+ bundled MKL)
  <openseesmp-dir>  {app}\\openseesmp  - openseesmp.pyd (+ Intel MPI + MKL)
                                         optional; pass "" / omit if absent

It drops two files in the venv's site-packages:

  _ladruno_opensees_boot.py   - the real logic (readable, multi-line)
  ladruno_opensees.pth        - one line: `import _ladruno_opensees_boot`

site.py exec()'s the .pth's `import` line at interpreter startup, which
runs the boot module. The boot module:

  * puts bin\\ and openseesmp\\ on sys.path (so both modules import), and
  * registers each dir via os.add_dll_directory so their bundled DLLs
    (MKL for opensees; Intel MPI + libfabric + MKL for openseesmp) resolve
    PROCESS-LOCALLY -- no global PATH change, so it cannot shadow the
    oneAPI impi.dll the Tcl OpenSeesSP/MP.exe rely on.

The os.add_dll_directory handles are kept in a module-global list so they
are not garbage-collected (which would remove the dir from the search path).

The legacy `openseespy` / `openseespy.opensees` alias -> our sequential
`opensees` is preserved, but SKIPPED under MPI: eagerly importing the
sequential runtime inside an `mpiexec ... import openseesmp` rank would
load two OpenSees runtimes into one process. Intel MPI / Hydra set
PMI_RANK / PMI_SIZE per rank, which we detect.

The generated wiring is PASSIVE: it registers search locations at startup
(sys.path, add_dll_directory, process-local PATH) and imports NOTHING. The
`openseespy` alias is resolved lazily by a meta_path finder, so the first
thing that actually loads `opensees.pyd` is the user's own import.

It did not used to be. An eager `import opensees` at interpreter startup
cost us twice over, and both bills are documented:

  * DLL LOCK -- every Python in the venv (VS Code's Black/isort/pylint
    lsp_server, Jupyter kernels) loaded the .pyd and pinned the install's
    MKL DLLs, so the next installer upgrade failed with "DeleteFile
    failed; code 5" (BUILD_GOTCHAS sec 5, whose "permanent fix" is exactly
    this change).
  * sys.modules HIJACK -- `opensees` was pinned before any user code ran,
    so a worktree build's own `sys.path.insert(0, dist/bin)` bootstrap was
    a no-op in any venv this script had wired (LEDGER_quirks: "An INSTALLED
    Ladruno hijacks `import opensees` in every venv it has wired").

Deferring the import fixes both, and the `sys.path.insert` bootstrap works
on its own again. `LADRUNO_OPENSEES_BIN` / `LADRUNO_OPENSEESMP_BIN` remain
as a deliberate override of the baked-in dirs -- now a convenience rather
than the only escape hatch:

    set LADRUNO_OPENSEES_BIN=<worktree>\\dist\\bin
    python -c "import opensees; print(opensees.ladrunoBuild())"

Only the installer (installer.iss) bakes in the Program-Files install dirs;
`wire_pyenv.ps1`'s own dev venvs point straight at a worktree's dist\\bin.
"""
import sys
import sysconfig
from pathlib import Path

BOOT_TEMPLATE = '''\
# Auto-generated by Ladruno wire_venv_pth.py - do not edit by hand.
# Makes BOTH `import opensees` and `import openseesmp` work from this venv.
import os, sys

# LADRUNO_OPENSEES_BIN / LADRUNO_OPENSEESMP_BIN override the baked-in install
# dirs when set -- an escape hatch so a worktree build can win in a venv this
# script wired to an installed Ladruno, without re-running the wirer (which
# would re-pin the .pth for every OTHER session using this venv). See the
# LEDGER_quirks "An INSTALLED Ladruno hijacks `import opensees`" entry.
_dirs = [
    os.environ.get("LADRUNO_OPENSEES_BIN") or {bin_repr},     # opensees.pyd  (+ bundled MKL)
    os.environ.get("LADRUNO_OPENSEESMP_BIN") or {mp_repr},    # openseesmp.pyd (+ Intel MPI + MKL); "" if not installed
]

# Keep the add_dll_directory handles alive for the whole process: if the
# returned object is GC'd the directory is removed from the DLL search path.
#
# os.add_dll_directory lets Python load opensees.pyd / openseesmp.pyd and
# their direct deps. But it is NOT enough for openseesmp: at MPI_Init,
# impi.dll itself does a bare LoadLibrary("libfabric.dll") (+ OFI provider),
# and that transitive load searches PATH, not the add_dll_directory set.
# So we ALSO prepend the dirs to this process's in-memory PATH. This is
# process-local (only this Python process + its children, e.g. spawned by
# the bundled mpiexec) -- it does NOT modify the user/system PATH, so it
# cannot shadow the oneAPI impi.dll the Tcl OpenSeesSP/MP.exe rely on.
_dll_cookies = []
for _d in _dirs:
    if _d and os.path.isdir(_d):
        if _d not in sys.path:
            sys.path.insert(0, _d)
        try:
            _dll_cookies.append(os.add_dll_directory(_d))
        except (OSError, AttributeError):
            pass
        _parts = os.environ.get("PATH", "").split(os.pathsep)
        if _d not in _parts:
            os.environ["PATH"] = _d + os.pathsep + os.environ.get("PATH", "")

# `openseespy` / `openseespy.opensees` -> our sequential `opensees`, so
# tools that hardcode `import openseespy.opensees` (apeGmsh, STKO helpers,
# openseespy-flavored examples) get THIS build (MPCO/HDF5) rather than a
# vanilla pip openseespy. Skipped under MPI (PMI_RANK/PMI_SIZE set by
# Intel MPI/Hydra) so `import openseesmp` ranks stay a single runtime.
#
# PASSIVE (this is the point of the file): the alias is resolved by a meta_path
# finder that does nothing until something actually asks for `openseespy`. The
# previous version did `import opensees` RIGHT HERE, at interpreter startup, and
# that one line caused both of the problems this wiring is notorious for:
#
#   1. DLL LOCK. Every Python in the venv -- VS Code's Black/isort/pylint
#      lsp_server, linters, Jupyter kernels -- loaded opensees.pyd and pinned the
#      install's MKL DLLs, so the next installer UPGRADE died with
#      "DeleteFile failed; code 5" (BUILD_GOTCHAS sec 5). Nothing here loads a
#      DLL any more: sys.path / add_dll_directory / PATH only REGISTER search
#      locations, they do not load anything.
#   2. sys.modules HIJACK. The eager import pinned `opensees` before any user
#      code ran, so a worktree's own `sys.path.insert(0, dist/bin)` bootstrap was
#      a no-op and you needed LADRUNO_OPENSEES_BIN to escape it (LEDGER_quirks
#      "An INSTALLED Ladruno hijacks `import opensees`"). Deferred, the insert
#      wins again on its own -- the env var stays as an override, not a crutch.
if not (os.environ.get("PMI_RANK") or os.environ.get("PMI_SIZE")):

    class _LadrunoOpenSeesPyAlias:
        """Resolve `openseespy[.opensees]` to this build's `opensees`, on demand.

        Registered ahead of the stock finders so it still beats a pip-installed
        openseespy, exactly as the eager version did.
        """

        _NAMES = ("openseespy", "openseespy.opensees")

        @classmethod
        def find_spec(cls, name, path=None, target=None):
            if name not in cls._NAMES:
                return None
            import importlib.util
            return importlib.util.spec_from_loader(name, cls)

        @staticmethod
        def create_module(spec):
            # First touch of the name: NOW pay for the real import.
            import opensees as _ops
            _ops.opensees = _ops
            # Pre-seed the submodule so `import openseespy.opensees` resolves
            # without needing openseespy to be a package -- CPython's
            # _find_and_load_unlocked re-checks sys.modules after importing the
            # parent (the branch its source comments "Crazy side-effects!").
            sys.modules.setdefault("openseespy.opensees", _ops)
            return _ops

        @staticmethod
        def exec_module(module):
            pass          # `opensees` already executed itself; aliasing only

    sys.meta_path.insert(0, _LadrunoOpenSeesPyAlias)
'''


def main() -> int:
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print("usage: wire_venv_pth.py <bin-dir> [<openseesmp-dir>]",
              file=sys.stderr)
        return 2

    bin_dir = sys.argv[1]
    mp_dir = sys.argv[2] if len(sys.argv) == 3 else ""

    site_packages = Path(sysconfig.get_paths()["purelib"])
    if not site_packages.is_dir():
        print(f"site-packages not found: {site_packages}", file=sys.stderr)
        return 1

    boot = site_packages / "_ladruno_opensees_boot.py"
    boot.write_text(
        BOOT_TEMPLATE.format(bin_repr=repr(bin_dir), mp_repr=repr(mp_dir)),
        encoding="ascii",
    )

    pth = site_packages / "ladruno_opensees.pth"
    pth.write_text("import _ladruno_opensees_boot\n", encoding="ascii")

    print(str(pth))
    print(f"  bin        : {bin_dir}")
    print(f"  openseesmp : {mp_dir or '(not installed)'}")

    if sys.version_info[:2] != (3, 12):
        v = f"{sys.version_info.major}.{sys.version_info.minor}"
        print(f"WARNING: this venv is Python {v}; the .pyd modules are "
              f"built for 3.12", file=sys.stderr)
        return 3

    return 0


if __name__ == "__main__":
    sys.exit(main())
