"""Wire a venv so BOTH `import opensees` and `import openseesmp` work.

Invoked by installer.iss at install time:
    <venv>\\Scripts\\python.exe wire_venv_pth.py <bin-dir> [<openseesmp-dir>]

  <bin-dir>         {app}\\bin         - opensees.pyd (+ bundled MKL)
  <openseesmp-dir>  {app}\\openseesmp  - openseesmp.pyd (+ Intel MPI + MKL)
                                         optional; pass "" / omit if absent

It drops two files in the venv's site-packages:

  _ladruno_opensees_boot.py   - the real logic (readable, multi-line)
  ladruno_opensees.pth        - one line: `import _ladruno_opensees_boot`

site.py exec()'s the .pth's `import` line at interpreter startup, which
runs the boot module. The boot module:

  * puts bin\\ and openseesmp\\ on sys.path (so both modules import), and
  * registers each dir via os.add_dll_directory so their bundled DLLs
    (MKL for opensees; Intel MPI + libfabric + MKL for openseesmp) resolve
    PROCESS-LOCALLY -- no global PATH change, so it cannot shadow the
    oneAPI impi.dll the Tcl OpenSeesSP/MP.exe rely on.

The os.add_dll_directory handles are kept in a module-global list so they
are not garbage-collected (which would remove the dir from the search path).

The legacy `openseespy` / `openseespy.opensees` alias -> our sequential
`opensees` is preserved, but SKIPPED under MPI: eagerly importing the
sequential runtime inside an `mpiexec ... import openseesmp` rank would
load two OpenSees runtimes into one process. Intel MPI / Hydra set
PMI_RANK / PMI_SIZE per rank, which we detect.
"""
import sys
import sysconfig
from pathlib import Path

BOOT_TEMPLATE = '''\
# Auto-generated by Ladruno wire_venv_pth.py - do not edit by hand.
# Makes BOTH `import opensees` and `import openseesmp` work from this venv.
import os, sys

_dirs = [
    {bin_repr},   # opensees.pyd  (+ bundled MKL)
    {mp_repr},    # openseesmp.pyd (+ Intel MPI + MKL); "" if not installed
]

# Keep the add_dll_directory handles alive for the whole process: if the
# returned object is GC'd the directory is removed from the DLL search path.
#
# os.add_dll_directory lets Python load opensees.pyd / openseesmp.pyd and
# their direct deps. But it is NOT enough for openseesmp: at MPI_Init,
# impi.dll itself does a bare LoadLibrary("libfabric.dll") (+ OFI provider),
# and that transitive load searches PATH, not the add_dll_directory set.
# So we ALSO prepend the dirs to this process's in-memory PATH. This is
# process-local (only this Python process + its children, e.g. spawned by
# the bundled mpiexec) -- it does NOT modify the user/system PATH, so it
# cannot shadow the oneAPI impi.dll the Tcl OpenSeesSP/MP.exe rely on.
_dll_cookies = []
for _d in _dirs:
    if _d and os.path.isdir(_d):
        if _d not in sys.path:
            sys.path.insert(0, _d)
        try:
            _dll_cookies.append(os.add_dll_directory(_d))
        except (OSError, AttributeError):
            pass
        _parts = os.environ.get("PATH", "").split(os.pathsep)
        if _d not in _parts:
            os.environ["PATH"] = _d + os.pathsep + os.environ.get("PATH", "")

# `openseespy` / `openseespy.opensees` -> our sequential `opensees`, so
# tools that hardcode `import openseespy.opensees` (apeGmsh, STKO helpers,
# openseespy-flavored examples) get THIS build (MPCO/HDF5) rather than a
# vanilla pip openseespy. Skipped under MPI (PMI_RANK/PMI_SIZE set by
# Intel MPI/Hydra) so `import openseesmp` ranks stay a single runtime.
if not (os.environ.get("PMI_RANK") or os.environ.get("PMI_SIZE")):
    try:
        import opensees as _ops
        sys.modules["openseespy"] = _ops
        sys.modules["openseespy.opensees"] = _ops
        _ops.opensees = _ops
    except Exception:
        pass
'''


def main() -> int:
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print("usage: wire_venv_pth.py <bin-dir> [<openseesmp-dir>]",
              file=sys.stderr)
        return 2

    bin_dir = sys.argv[1]
    mp_dir = sys.argv[2] if len(sys.argv) == 3 else ""

    site_packages = Path(sysconfig.get_paths()["purelib"])
    if not site_packages.is_dir():
        print(f"site-packages not found: {site_packages}", file=sys.stderr)
        return 1

    boot = site_packages / "_ladruno_opensees_boot.py"
    boot.write_text(
        BOOT_TEMPLATE.format(bin_repr=repr(bin_dir), mp_repr=repr(mp_dir)),
        encoding="ascii",
    )

    pth = site_packages / "ladruno_opensees.pth"
    pth.write_text("import _ladruno_opensees_boot\n", encoding="ascii")

    print(str(pth))
    print(f"  bin        : {bin_dir}")
    print(f"  openseesmp : {mp_dir or '(not installed)'}")

    if sys.version_info[:2] != (3, 12):
        v = f"{sys.version_info.major}.{sys.version_info.minor}"
        print(f"WARNING: this venv is Python {v}; the .pyd modules are "
              f"built for 3.12", file=sys.stderr)
        return 3

    return 0


if __name__ == "__main__":
    sys.exit(main())
