"""Parse the Lemaitre formulation profiler HDF5s (bbar / eas) and write the full
per-parameter table to Ladruno_implementation/lemaitre_validation/profiler_dump.md.

Run AFTER lemaitre_validation_figures.py F (which writes prof_bbar.h5 / prof_eas.h5
into %TEMP% with `profiler start -deep -perStep`).
"""
import os
import h5py

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Ladruno_implementation", "lemaitre_validation", "profiler_dump.md")
TMP = os.environ.get("TEMP", "/tmp")
FILES = {"bbar": os.path.join(TMP, "prof_bbar.h5"), "eas": os.path.join(TMP, "prof_eas.h5")}


def load(path):
    out = {"meta": {}, "phases": {}, "elem": {}, "mem": {}, "nstep": 0}
    with h5py.File(path, "r") as f:
        run = f["runs"][list(f["runs"])[0]]
        out["meta"] = dict(run.attrs)
        if "memory" in run:
            out["mem"] = dict(run["memory"].attrs)
        if "series" in run:
            try:
                out["nstep"] = int(run["series"]["step"].shape[0])
            except Exception:
                pass

        def walk(g, p=""):
            for k in g:
                it = g[k]
                if isinstance(it, h5py.Group):
                    pp = p + "/" + k if p else k
                    a = dict(it.attrs)
                    if "wall_ns" in a:
                        out["phases"][pp] = (int(a.get("calls", 0)), int(a.get("wall_ns", 0)))
                    walk(it, pp)
                elif k == "elem_by_type":
                    for row in it[()]:
                        out["elem"].setdefault(p, []).append(
                            (int(row["classTag"]), int(row["count"]),
                             int(row["wall_ns"]), float(row["wall_ns_per_elem"])))
        if "rollup" in run and "root" in run["rollup"]:
            walk(run["rollup"]["root"], "root")
    return out


D = {k: load(v) for k, v in FILES.items()}
L = []
L.append("# Profiler dump — bbar vs eas (DEN notched bar, h=2)\n")
L.append("Generated by `Ladruno_scripts/make_profiler_dump.py` from `profiler start -deep "
         "-perStep` + `report`. Companion to README §4.4.\n")

# run header
mk = [("nDOF", "nDOF"), ("nElem", "nElem"), ("nNode", "nNode"), ("nnz", "nnz"),
      ("nSteps", "nSteps"), ("solver", "solver"), ("integrator", "integrator"),
      ("algorithm", "algorithm"), ("threads", "threads"),
      ("wall_ms_total", "wall_ms_total"), ("cpu_ms_total", "cpu_ms_total"),
      ("dt_cr", "dt_cr"), ("timestamp", "timestamp")]
L.append("## Run header (`RunMeta`)\n")
L.append("| parameter | bbar | eas |")
L.append("|---|---|---|")
for label, key in mk:
    b = D["bbar"]["meta"].get(key, ""); e = D["eas"]["meta"].get(key, "")
    L.append(f"| {label} | {b} | {e} |")

# phases
L.append("\n## Phase rollup — wall_ms / calls\n")
L.append("| phase | bbar (ms / calls) | eas (ms / calls) |")
L.append("|---|---|---|")
for p in sorted(set(D["bbar"]["phases"]) | set(D["eas"]["phases"])):
    b = D["bbar"]["phases"].get(p); e = D["eas"]["phases"].get(p)
    bs = f"{b[1]/1e6:.1f} / {b[0]}" if b else "—"
    es = f"{e[1]/1e6:.1f} / {e[0]}" if e else "—"
    L.append(f"| `{p}` | {bs} | {es} |")

# elem_by_type
L.append("\n## elem_by_type — classTag 33002 (LadrunoBrick)\n")
L.append("| scope | bbar: count · wall_ms · µs/elem | eas: count · wall_ms · µs/elem |")
L.append("|---|---|---|")
for p in sorted(set(D["bbar"]["elem"]) | set(D["eas"]["elem"])):
    bb = next((r for r in D["bbar"]["elem"].get(p, []) if r[0] == 33002), None)
    ee = next((r for r in D["eas"]["elem"].get(p, []) if r[0] == 33002), None)
    bs = f"{bb[1]} · {bb[2]/1e6:.1f} · **{bb[3]/1e3:.1f}**" if bb else "—"
    es = f"{ee[1]} · {ee[2]/1e6:.1f} · **{ee[3]/1e3:.1f}**" if ee else "—"
    L.append(f"| `{p}` | {bs} | {es} |")

# memory
L.append("\n## Memory snapshot\n")
L.append("| field | bbar | eas |")
L.append("|---|---|---|")
for k in ["peak_bytes", "matrix_live", "vector_live", "id_live"]:
    L.append(f"| {k} | {D['bbar']['mem'].get(k, 0)} | {D['eas']['mem'].get(k, 0)} |")

L.append("\n## Caveats\n")
L.append("- **µs/elem** (per-element tangent) is the clean comparator — same op, same "
         "instrumentation. eas (1 GP + Kstab) < bbar (8 GP).")
L.append("- Totals (`cpu_ms_total`, `*/step` wall) are unreliable on Windows (the profiler "
         "CPU clock is a Win32 stub); trust the python wall-clock and µs/elem.")
L.append("- `nElem`/`nNode` populate only with the `OpenSeesCommands.cpp` patch that sets them "
         "from the live `Domain` (additive `// Ladruno` hook) — **requires a rebuild**; they "
         "read 0 on pre-patch binaries.")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("wrote", OUT)
print("bbar nSteps=", D["bbar"]["meta"].get("nSteps"), " nElem=", D["bbar"]["meta"].get("nElem"))
