// Auto-generated file - do not edit manually
// Generated by gen_ASD_material_definitions_CPP.py

// =========================================
// Standard Plasticity Models
// =========================================

createASDPlasticMaterial3D<
        StiffSoil_EL, 
        StiffSoilShear_YF<
            EpsQpShear
            >, 
        StiffSoilShear_PF<
            EpsQpShear
            >
        > (instance_tag, yf_type, pf_type, el_type, iv_type, instance_pointers, available_models);

createASDPlasticMaterial3D<
        StiffSoil_EL, 
        StiffSoilCap_YF<
            CapPressure
            >, 
        StiffSoilCap_PF<
            CapPressure
            >
        > (instance_tag, yf_type, pf_type, el_type, iv_type, instance_pointers, available_models);

