#!/usr/bin/python
from itertools import product

# ============================================================================
# Standard Elasticity Models
# ============================================================================
EL = [
    "LinearIsotropic3D_EL",
    # "DuncanChang_EL",
]

# ============================================================================
# Standard Yield Functions
# ============================================================================
YF = [
    "VonMises_YF",
    "DruckerPrager_YF",
    "MohrCoulomb_YF",
    # "TensionCutoff_YF",
]

# ============================================================================
# Standard Plastic Flow Directions
# ============================================================================
PF = [
    "VonMises_PF",
    "DruckerPrager_PF",
    # "ConstantDilatancy_PF",
    "MohrCoulomb_PF"
]

# ============================================================================
# Possible combinations of IV with YFs
# ============================================================================
IV_YF = {}

IV_YF["VonMises_YF"] = [
    "BackStress<TensorLinearHardeningFunction>,YieldStress<ScalarLinearHardeningFunction>",
    "BackStress<ArmstrongFrederickHardeningFunction>,YieldStress<ScalarLinearHardeningFunction>",
]

IV_YF["DruckerPrager_YF"] = [
    "BackStress<TensorLinearHardeningFunction>,DP_cohesion<ScalarLinearHardeningFunction>",
    "BackStress<ArmstrongFrederickHardeningFunction>,DP_cohesion<ScalarLinearHardeningFunction>",
]

IV_YF["MohrCoulomb_YF"] = [
    "BackStress<NullHardeningTensorFunction>"
]

IV_YF["TensionCutoff_YF"] = [
    "BackStress<NullHardeningTensorFunction>"
]

# ============================================================================
# Possible combinations of IV with PFs
# ============================================================================
IV_PF = {
    "VonMises_PF": [
    "BackStress<NullHardeningTensorFunction>",
    "BackStress<TensorLinearHardeningFunction>",
    "BackStress<ArmstrongFrederickHardeningFunction>",
    ],
    "DruckerPrager_PF":
    [
    "BackStress<TensorLinearHardeningFunction>, DP_cohesion<ScalarLinearHardeningFunction>",
    "BackStress<ArmstrongFrederickHardeningFunction>, DP_cohesion<ScalarLinearHardeningFunction>",
    ]
}

IV_PF["ConstantDilatancy_PF"] = IV_PF["VonMises_PF"]

IV_PF["MohrCoulomb_PF"] = [
    "BackStress<NullHardeningTensorFunction>"
]


# ============================================================================
# Template for standard models (YF and PF have separate IV template arguments)
# ============================================================================
template = """
createASDPlasticMaterial3D<
        {EL}, 
        {YF}<
            {IV_YF}
            >, 
        {PF}<
            {IV_PF}
            >
        > (instance_tag, yf_type, pf_type, el_type, iv_type, instance_pointers, available_models);
"""


# ============================================================================
# STIFF SOIL MODEL DEFINITIONS
# ============================================================================

# Template for Stiff Soil models (YF and PF share the same IV type)
stiffsoil_template = """
createASDPlasticMaterial3D<
        {EL}, 
        {YF}<
            {IV}
            >, 
        {PF}<
            {IV}
            >
        > (instance_tag, yf_type, pf_type, el_type, iv_type, instance_pointers, available_models);
"""

# Stiff Soil model configurations
# Each entry is (Elasticity, YieldFunction, PlasticFlow, InternalVariable)
STIFFSOIL_MODELS = [
    # Deviatoric (Shear) mechanism
    {
        "EL": "StiffSoil_EL",
        "YF": "StiffSoilShear_YF",
        "PF": "StiffSoilShear_PF",
        "IV": "EpsQpShear"
    },
    # Cap (Volumetric) mechanism
    {
        "EL": "StiffSoil_EL",
        "YF": "StiffSoilCap_YF",
        "PF": "StiffSoilCap_PF",
        "IV": "CapPressure"
    },
    # Cap mechanism with linear hardening (alternative)
    {
        "EL": "StiffSoil_EL",
        "YF": "StiffSoilCap_YF",
        "PF": "StiffSoilCap_PF",
        "IV": "CapPressureLinear"
    },
]


# ============================================================================
# Generate output file
# ============================================================================
with open("ASD_material_definitions.cpp", "w") as fid:
    
    # Write header
    fid.write("// Auto-generated file - do not edit manually\n")
    fid.write("// Generated by gen_ASD_material_definitions_CPP.py\n\n")
    
    # -------------------------------------------------------------------------
    # Standard models
    # -------------------------------------------------------------------------
    fid.write("// =========================================\n")
    fid.write("// Standard Plasticity Models\n")
    fid.write("// =========================================\n")
    
    for el, yf, pf in product(EL, YF, PF):
        for iv_yf in IV_YF[yf]:
            for iv_pf in IV_PF[pf]:
                fid.write(template.format(EL=el, YF=yf, PF=pf, IV_YF=iv_yf, IV_PF=iv_pf))
    
    # -------------------------------------------------------------------------
    # Stiff Soil models
    # -------------------------------------------------------------------------
    fid.write("\n// =========================================\n")
    fid.write("// Stiff Soil (Hardening Soil) Models\n")
    fid.write("// =========================================\n")
    
    for model in STIFFSOIL_MODELS:
        fid.write(stiffsoil_template.format(**model))

print("Generated ASD_material_definitions.cpp")
