#!/usr/bin/env python3
"""Build-control ledgers as per-WP fragments (WP-161). Dependency-free.

The three ledgers (`LEDGER_implementations.md`, `LEDGER_quirks.md`,
`LEDGER_vanilla_files.md`) used to be single files that every work package
edited at the same anchor, so every pair of open PRs conflicted on them (55 of
64 conflicted merge-ups in the 60 PRs before WP-161 were ledger-only). Now each
entry is its own file:

    Ladruno_implementation/ledger/<kind>/<KEY>-<slug>.md     kind = implementations | quirks | vanilla
    Ladruno_implementation/ledger/<kind>/_template.md        the ledger's intro + conventions

KEY is `WP-<n>` for work-package entries; content older than the WP era uses
`ADR-<n>`, `PR-<n>` or `LEGACY`. A fragment is YAML front matter + a markdown
body, and the body is exactly what the old ledger held:

    implementations   one table row (section: table), or one build-history bullet (section: history)
    quirks            one `###` (or legacy `##`) entry, heading included
    vanilla           one PR's rows, one row per file (table: main | upstreamable)

`build` renders the three ledgers into `Ladruno_implementation/ledger/_build/`
(gitignored; CI uploads it as the `ledgers` artifact). The committed
`LEDGER_*.md` are short stubs so `[[LEDGER_quirks]]` wiki-links still resolve.

Commands:
    python ci/ledger.py build [--out DIR]
        Render all three ledgers. Newest WP first for implementations rows and
        quirks (by `date`), then the migrated entries in their old order; vanilla
        rows are grouped by file.
    python ci/ledger.py split [--ref REV]
        ONE-TIME migration: read the full LEDGER_*.md (working tree, or REV),
        write the templates + one fragment per entry, replace the ledgers with
        stubs. Refuses to split a stub. Keeps fragments that are not migrated
        (no `legacy_seq`), e.g. a WP's own fragment written before the split.
    python ci/ledger.py migrate --from-diff BASE [--head REV] [--wp WP-n] [--dry-run]
        For a branch that still edited the old single-file ledgers: diff the
        ledgers BASE..REV entry by entry, write the added entries as new
        fragments and apply edits of existing entries to their fragments.
    python ci/ledger.py roundtrip [--ref REV]
        Prove build(split(ledgers)) has the same entries and template as the
        ledgers (the source the stubs record, or REV). Also run by
        ci/test_ledger.py.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import difflib
import json
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMPL_DIR = "Ladruno_implementation"
FRAG_DIR = f"{IMPL_DIR}/ledger"
BUILD_DIR = f"{FRAG_DIR}/_build"
TEMPLATE = "_template.md"

KINDS = {
    "implementations": {"ledger": "LEDGER_implementations.md", "tables": ("table",),
                        "history": "## Documentation / ADR PRs"},
    "quirks": {"ledger": "LEDGER_quirks.md", "anchor": "## Quirks"},
    "vanilla": {"ledger": "LEDGER_vanilla_files.md", "tables": ("main", "upstreamable")},
}

# front-matter keys, in the order they are written
KEYS = ("wp", "title", "pr", "date", "status", "files", "class_tags", "banner",
        "section", "table", "legacy_seq")
KEY_RE = re.compile(r"^(WP-\d{1,4}[a-z]?|ADR-\d{1,4}[a-z]?|PR-\d{1,4}|LEGACY)$")
NAME_RE = re.compile(r"^(?P<key>WP-\d{1,4}[a-z]?|ADR-\d{1,4}[a-z]?|PR-\d{1,4}|LEGACY)-(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

GENERATED = "<!-- GENERATED by `python ci/ledger.py build` from Ladruno_implementation/ledger/{kind}/ -- do not edit; write a fragment -->"
GENERATED_RE = re.compile(r"^<!-- GENERATED by `python ci/ledger.py build`.*-->$")
STUB_MARK = "<!-- ledger-stub"
STUB_SOURCE_RE = re.compile(r"<!-- ledger-stub kind=(\w+) split-source=([0-9a-f]{7,40}|worktree) -->")
PLACEHOLDER_RE = re.compile(r"^<!-- ledger:(rows|history|entries)(?: ([\w-]+))? -->$")

SEP_RE = re.compile(r"^\|(?:\s*:?-{3,}:?\s*\|)+\s*$")
HEADING_RE = re.compile(r"^#{2,3} \S")
FENCE_RE = re.compile(r"^\s*(```|~~~)")
CELL_SPLIT = re.compile(r"(?<!\\)\|")
WP_IN = re.compile(r"\bWP[- ](\d{1,4}[a-z]?)\b")
ADR_IN = re.compile(r"\bADR[- ]?(\d{1,4}[a-z]?)\b")
PR_IN = re.compile(r"(?:/pull/|#)(\d{1,4})\b")


class LedgerError(RuntimeError):
    pass


# --------------------------------------------------------------------------
# fragments: front matter (a strict YAML subset) + body
# --------------------------------------------------------------------------
@dataclass
class Fragment:
    kind: str
    name: str                   # file stem
    meta: dict
    body: str
    path: Path | None = None

    @property
    def legacy(self) -> bool:
        return "legacy_seq" in self.meta

    def text(self) -> str:
        return dump_fragment(self.meta, self.body)


def _scalar(raw: str):
    """A front-matter value: JSON (quoted string, number, list, true/false/null) or a bare string."""
    if raw == "":
        return ""
    if raw[0] in "[{\"" or raw in ("true", "false", "null") or re.fullmatch(r"-?\d+", raw):
        try:
            return json.loads(raw)
        except json.JSONDecodeError as e:
            raise LedgerError(f"bad front-matter value {raw!r}: {e}") from None
    if raw[0] in "'&*!|>%@`#" or ": " in raw or " #" in raw:
        raise LedgerError(f"bare front-matter value {raw!r} is not plain YAML; quote it as JSON")
    return raw


def parse_fragment(text: str) -> tuple[dict, str]:
    """(meta, body). Front matter: `key: value` lines between two `---` lines."""
    lines = text.replace("\r\n", "\n").split("\n")
    if not lines or lines[0] != "---":
        raise LedgerError("no front matter (the first line must be ---)")
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise LedgerError("front matter is not closed by a --- line") from None
    meta: dict = {}
    for ln in lines[1:end]:
        if not ln.strip():
            continue
        m = re.match(r"^([a-z_]+):(?: (.*))?$", ln)
        if not m:
            raise LedgerError(f"bad front-matter line {ln!r} (one `key: value` per line)")
        key = m.group(1)
        if key in meta:
            raise LedgerError(f"front-matter key {key!r} given twice")
        meta[key] = _scalar((m.group(2) or "").strip())
    return meta, "\n".join(lines[end + 1:]).strip("\n")


def _dump_value(v) -> str:
    if isinstance(v, str) and (DATE_RE.match(v) or KEY_RE.match(v)):
        return v
    return json.dumps(v, ensure_ascii=False)


def dump_fragment(meta: dict, body: str) -> str:
    keys = [k for k in KEYS if k in meta] + sorted(k for k in meta if k not in KEYS)
    head = "\n".join(f"{k}: {_dump_value(meta[k])}" for k in keys)
    return f"---\n{head}\n---\n{body.strip(chr(10))}\n"


def frag_dir(root: Path, kind: str) -> Path:
    return root / FRAG_DIR / kind


def load_fragments(root: Path, kind: str) -> list[Fragment]:
    out = []
    d = frag_dir(root, kind)
    if not d.is_dir():
        return out
    for p in sorted(d.glob("*.md")):
        if p.name.startswith("_"):
            continue
        meta, body = parse_fragment(p.read_text(encoding="utf-8"))
        out.append(Fragment(kind, p.stem, meta, body, p))
    return out


def load_template(root: Path, kind: str) -> str:
    p = frag_dir(root, kind) / TEMPLATE
    if not p.exists():
        raise LedgerError(f"{p.relative_to(root).as_posix()} is missing (run `python ci/ledger.py split` once)")
    return p.read_text(encoding="utf-8").replace("\r\n", "\n")


# --------------------------------------------------------------------------
# markdown helpers
# --------------------------------------------------------------------------
def is_row(line: str) -> bool:
    return line.startswith("|")


def cells(row: str) -> list[str]:
    parts = CELL_SPLIT.split(row.strip())
    if parts and parts[0] == "":
        parts = parts[1:]
    if parts and parts[-1].strip() == "":
        parts = parts[:-1]
    return [c.strip() for c in parts]


def plain(md: str) -> str:
    """Markdown -> plain text, for titles."""
    s = re.sub(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]", lambda m: m.group(2) or m.group(1), md)
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)
    s = s.replace("**", "").replace("`", "").replace("\\|", "|")
    s = re.sub(r"^#+\s*", "", s)
    return " ".join(s.split())


def shorten(s: str, n: int = 160) -> str:
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def slugify(s: str, n: int = 48) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    if len(s) > n:
        s = s[:n].rsplit("-", 1)[0] if "-" in s[:n] else s[:n]
    return s.strip("-") or "entry"


def _key_from(*texts: str) -> str | None:
    for rx, fmt in ((WP_IN, "WP-{}"), (ADR_IN, "ADR-{}")):
        for t in texts:
            m = rx.search(t or "")
            if m:
                return fmt.format(m.group(1))
    return None


def _pr_from(*texts: str) -> str | None:
    for t in texts:
        m = PR_IN.search(t or "")
        if m:
            return f"PR-{m.group(1)}"
    return None


def wp_number(key: str) -> int:
    m = re.match(r"^WP-(\d+)", key or "")
    return int(m.group(1)) if m else 0


# --------------------------------------------------------------------------
# parse a single-file ledger into (template, entries)
# --------------------------------------------------------------------------
@dataclass
class Entry:
    section: str        # rows table name / "history" / "entries"
    text: str
    meta: dict = field(default_factory=dict)


def _collapse_blank(lines: list[str]) -> str:
    out: list[str] = []
    for ln in lines:
        if ln.strip() == "" and out and out[-1].strip() == "":
            continue
        out.append(ln)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


def _strip_generated(lines: list[str]) -> list[str]:
    return [ln for ln in lines if not GENERATED_RE.match(ln.strip())]


def parse_ledger(kind: str, text: str) -> tuple[str, list[Entry]]:
    """Split a whole ledger file into its template (everything that is not an
    entry, with placeholders where the entries go) and its entries, in order."""
    if STUB_MARK in text:
        raise LedgerError(f"{KINDS[kind]['ledger']} is a stub, not a ledger -- nothing to parse")
    lines = _strip_generated(text.replace("\r\n", "\n").split("\n"))
    if kind == "quirks":
        return _parse_quirks(lines)
    return _parse_tables(kind, lines)


def _parse_quirks(lines: list[str]) -> tuple[str, list[Entry]]:
    anchor = KINDS["quirks"]["anchor"]
    try:
        q = next(i for i, ln in enumerate(lines) if ln.rstrip() == anchor)
    except StopIteration:
        raise LedgerError(f"quirks ledger has no '{anchor}' heading") from None
    tpl = lines[: q + 1]
    entries: list[Entry] = []
    cur: list[str] | None = None
    fence = None
    for ln in lines[q + 1:]:
        fm = FENCE_RE.match(ln)
        if fm:
            fence = None if fence == fm.group(1) else (fence or fm.group(1))
        if fence is None and not fm and HEADING_RE.match(ln):
            if cur is not None:
                entries.append(Entry("entries", "\n".join(cur).strip("\n")))
            cur = [ln]
            continue
        if cur is None:
            if ln.strip():
                tpl.append(ln)              # prose between the anchor and the first entry
            continue
        cur.append(ln)
    if cur is not None:
        entries.append(Entry("entries", "\n".join(cur).strip("\n")))
    tpl += ["", "<!-- ledger:entries -->"]
    return _collapse_blank(tpl), entries


def _parse_tables(kind: str, lines: list[str]) -> tuple[str, list[Entry]]:
    names = KINDS[kind]["tables"]
    history = KINDS[kind].get("history")
    tpl: list[str] = []
    entries: list[Entry] = []
    in_ledger = False           # past the first "## Ledger" heading
    ti = -1                     # index of the current/last ledger table
    mode = None                 # None | "table" | "history"
    in_history = False
    history_placed = False
    i, n = 0, len(lines)

    def plain_row_follows(k):
        """True if the next non-blank line after k is a row that does not open a new table."""
        while k < n and not lines[k].strip():
            k += 1
        return k < n and is_row(lines[k]) and not (k + 1 < n and SEP_RE.match(lines[k + 1]))

    while i < n:
        ln = lines[i]
        if not in_ledger and ln.rstrip() == "## Ledger":
            in_ledger = True
        if history and ln.startswith(history):
            in_history = True
        # a ledger table starts: header row + separator
        if in_ledger and mode != "table" and ti + 1 < len(names) and is_row(ln) \
                and i + 1 < n and SEP_RE.match(lines[i + 1]):
            ti += 1
            tpl += [ln, lines[i + 1], f"<!-- ledger:rows {names[ti]} -->"]
            mode = "table"
            i += 2
            continue
        if mode == "table":
            if is_row(ln):
                entries.append(Entry(names[ti], ln.rstrip()))
                i += 1
                continue
            if not ln.strip() and plain_row_follows(i):
                i += 1                  # a blank line inside the table (a union-merge artefact)
                continue
            mode = None
        if mode == "history":
            if ln.startswith((" ", "\t")) and ln.strip():
                entries[-1].text += "\n" + ln.rstrip()
                i += 1
                continue
            mode = None
        if ti >= 0 and is_row(ln) and not (i + 1 < n and SEP_RE.match(lines[i + 1])):
            entries.append(Entry(names[ti], ln.rstrip()))      # an orphan row appended past the table
            i += 1
            continue
        if in_history and ln.startswith("- "):
            if not history_placed:
                tpl.append("<!-- ledger:history -->")
                history_placed = True
            entries.append(Entry("history", ln.rstrip()))
            mode = "history"
            i += 1
            continue
        if ti >= 0 and not ln.strip() and plain_row_follows(i):
            i += 1                      # blank lines between orphan rows
            continue
        tpl.append(ln)
        i += 1
    if ti + 1 != len(names):
        raise LedgerError(f"{KINDS[kind]['ledger']}: found {ti + 1} ledger table(s), expected {len(names)}")
    return _collapse_blank(tpl), entries


# --------------------------------------------------------------------------
# split: entries -> fragments
# --------------------------------------------------------------------------
def _unique(name: str, taken: set[str]) -> str:
    base, k = name, 2
    while name.lower() in taken:
        name = f"{base}-{k}"
        k += 1
    taken.add(name.lower())
    return name


def _name(key: str, title: str, taken: set[str]) -> str:
    t = title
    if key != "LEGACY":
        num = key.split("-", 1)[1]
        prefix = "(?:PR[- ]?|#)" if key.startswith("PR-") else key.split("-")[0] + "[- ]?"
        t = re.sub(r"^\W*" + prefix + re.escape(num) + r"\b\W*", "", t, flags=re.I)
    return _unique(f"{key}-{slugify(t)}", taken)


def impl_meta(text: str, section: str) -> dict:
    """Front matter for one implementations row or history bullet."""
    if section == "history":
        title = plain(text[2:])
        key = _key_from(text[:300]) or _pr_from(text[:200]) or "LEGACY"
        return {"wp": key, "title": shorten(title, 120), "section": "history"}
    c = cells(text)
    feature = c[0] if c else text
    bold = re.match(r"^\s*\*\*(.+?)\*\*", feature)
    title = plain(bold.group(1) if bold else feature)
    pr_cell = c[-1] if len(c) >= 2 else ""
    key = _key_from(feature) or _pr_from(pr_cell) or _key_from(text) or "LEGACY"
    meta = {"wp": key, "title": shorten(title)}
    prs = sorted({int(x) for x in PR_IN.findall(pr_cell)})
    if prs:
        meta["pr"] = ", ".join(f"#{p}" for p in prs)
    if len(c) == 6:
        meta["status"] = shorten(plain(c[4]), 80)
        tags = sorted(set(re.findall(r"\b[A-Z][A-Z0-9]*_TAG_\w+", c[2])))
        if tags:
            meta["class_tags"] = tags
    meta["section"] = "table"
    return meta


def quirk_meta(text: str) -> dict:
    head = text.split("\n", 1)[0]
    title = plain(head)
    key = _key_from(head) or _pr_from(head) or "LEGACY"     # the heading only: a body cites other WPs
    meta = {"wp": key, "title": shorten(title)}
    d = re.search(r"\b(20\d\d-\d\d-\d\d)\b", head)
    if d:
        meta["date"] = d.group(1)
    return meta


def split_entries(kind: str, entries: list[Entry], taken: set[str]) -> list[Fragment]:
    """Fragments for migrated entries, `legacy_seq` = position in the old file."""
    frags: list[Fragment] = []
    if kind in ("implementations", "quirks"):
        for seq, e in enumerate(entries, 1):
            meta = impl_meta(e.text, "history" if e.section == "history" else "table") \
                if kind == "implementations" else quirk_meta(e.text)
            meta["legacy_seq"] = seq
            name = _name(meta["wp"], meta["title"], taken)
            frags.append(Fragment(kind, name, meta, e.text))
        return frags
    # vanilla: one fragment per (table, PR cell); rows keep their own positions
    groups: dict[tuple[str, str], list[tuple[int, str]]] = {}
    for seq, e in enumerate(entries, 1):
        c = cells(e.text)
        pr_cell = " ".join(c[-1].split()) if len(c) >= 2 else ""
        groups.setdefault((e.section, pr_cell), []).append((seq, e.text))
    for (table, pr_cell), rows in groups.items():
        whys = {m for _, r in rows for m in WP_IN.findall(" ".join(cells(r)[1:-1]))}
        key = _key_from(pr_cell) if WP_IN.search(pr_cell) else None
        if key is None and len(whys) == 1:
            key = f"WP-{next(iter(whys))}"
        bare = re.fullmatch(r"#?(\d{1,4})", plain(pr_cell))
        key = key or _pr_from(pr_cell) or (f"PR-{bare.group(1)}" if bare else None) \
            or _key_from(pr_cell) or "LEGACY"
        files = [cells(r)[0] if cells(r) else "" for _, r in rows]
        title = plain(pr_cell) or "no PR recorded"
        meta = {"wp": key, "title": shorten(f"{title} -- {len(rows)} vanilla row(s)" if table == "main"
                                            else f"{title} -- upstreamable-table row(s)"),
                "files": files, "table": table, "legacy_seq": [s for s, _ in rows]}
        prs = sorted({int(x) for x in PR_IN.findall(pr_cell)} | ({int(bare.group(1))} if bare else set()))
        if prs:
            meta["pr"] = ", ".join(f"#{p}" for p in prs)
        # slug: what the PR cell says besides the PR link; else the first file's name
        what = re.sub(r"\[#?\d+\]\([^)]*\)|#\d+\b|^\d+$", " ", plain(re.sub(r"\[([^\]]*)\]\([^)]*\)", " ", pr_cell)))
        what = re.sub(r"^\W*" + re.escape(key) + r"\b", " ", what.strip(), flags=re.I)
        if not slugify(what, 40).strip("-") or slugify(what, 40) == "entry":
            what = Path(plain(files[0]).split(",")[0].split(" ")[0].strip("{}")).name or "rows"
        name = _name(key, what + ("" if table == "main" else " upstreamable"), taken)
        frags.append(Fragment("vanilla", name, meta, "\n".join(r for _, r in rows)))
    return frags


# --------------------------------------------------------------------------
# build: fragments -> ledger text
# --------------------------------------------------------------------------
def _new_key(f: Fragment):
    return (f.meta.get("date") or "", wp_number(f.meta.get("wp", "")), f.name)


def render(kind: str, template: str, frags: list[Fragment]) -> str:
    legacy = [f for f in frags if f.legacy]
    new = [f for f in frags if not f.legacy]
    blocks: dict[tuple[str, str], list[str]] = {}

    def seq(f):
        s = f.meta["legacy_seq"]
        return s[0] if isinstance(s, list) else s

    if kind == "quirks":
        ordered = sorted(new, key=_new_key, reverse=True) + sorted(legacy, key=seq)
        blocks[("entries", "")] = [f.body for f in ordered]
    elif kind == "implementations":
        rows_new = sorted((f for f in new if f.meta.get("section", "table") == "table"), key=_new_key, reverse=True)
        rows_old = sorted((f for f in legacy if f.meta.get("section", "table") == "table"), key=seq)
        hist_old = sorted((f for f in legacy if f.meta.get("section") == "history"), key=seq)
        hist_new = sorted((f for f in new if f.meta.get("section") == "history"), key=_new_key)
        blocks[("rows", "table")] = [f.body for f in rows_new + rows_old]
        blocks[("history", "")] = [f.body for f in hist_old + hist_new]
    else:
        per_table: dict[str, list[tuple[tuple, str, str]]] = {}
        for f in frags:
            table = f.meta.get("table", "main")
            rows = [r for r in f.body.split("\n") if r.strip()]
            seqs = f.meta.get("legacy_seq")
            for k, r in enumerate(rows):
                if f.legacy:
                    order = (0, seqs[k] if isinstance(seqs, list) and k < len(seqs) else seq(f), "", 0, "", k)
                else:
                    order = (1, 0, f.meta.get("date") or "", wp_number(f.meta.get("wp", "")), f.name, k)
                c = cells(r)
                per_table.setdefault(table, []).append((order, " ".join((c[0] if c else r).split()), r))
        for table, rows in per_table.items():
            first: dict[str, tuple] = {}
            for order, fk, _ in rows:
                if fk not in first or order < first[fk]:
                    first[fk] = order
            rows.sort(key=lambda t: (first[t[1]], t[0]))
            blocks[("rows", table)] = [r for _, _, r in rows]

    out: list[str] = []
    seen = set()
    for ln in template.replace("\r\n", "\n").rstrip("\n").split("\n"):
        m = PLACEHOLDER_RE.match(ln.strip())
        if not m:
            out.append(ln)
            continue
        key = (m.group(1), m.group(2) or "")
        seen.add(key)
        body = blocks.get(key, [])
        if m.group(1) == "entries":
            out.append("\n\n".join(body))
        else:
            out.extend(body)
    missing = [k for k, v in blocks.items() if v and k not in seen]
    if missing:
        raise LedgerError(f"{kind}: _template.md has no placeholder for {missing}")
    text = "\n".join(out).rstrip("\n") + "\n"
    # the GENERATED banner goes right after the front matter
    lines = text.split("\n")
    at = 0
    if lines and lines[0] == "---" and "---" in lines[1:]:
        at = lines.index("---", 1) + 1
    lines.insert(at, GENERATED.format(kind=kind))
    return "\n".join(lines)


def build(root: Path, out_dir: Path | None = None) -> dict[str, Path]:
    out_dir = out_dir or root / BUILD_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for kind, spec in KINDS.items():
        text = render(kind, load_template(root, kind), load_fragments(root, kind))
        p = out_dir / spec["ledger"]
        p.write_text(text, encoding="utf-8", newline="\n")
        written[kind] = p
    return written


# --------------------------------------------------------------------------
# stubs
# --------------------------------------------------------------------------
STUB_TITLES = {
    "implementations": "Ledger — our own implementations",
    "quirks": "Ledger — OpenSees quirks & gotchas",
    "vanilla": "Ledger — vanilla files we touched",
}


def render_stub(kind: str, source: str) -> str:
    led = KINDS[kind]["ledger"]
    return (
        f"---\ntitle: {STUB_TITLES[kind]} (stub)\nproject: Ladruno\ntags:\n  - ledger\n---\n\n"
        f"# {STUB_TITLES[kind]}\n\n"
        f"This file is a stub. Since WP-161 the ledger is one fragment per entry in\n"
        f"[`ledger/{kind}/`](ledger/{kind}/), named `WP-<nnn>-<slug>.md`.\n"
        f"**Never edit this file**; write a fragment (format: [`ledger/README.md`](ledger/README.md)).\n\n"
        f"- Read: `rg <pattern> Ladruno_implementation/ledger/{kind}/`\n"
        f"- Full ledger: `python ci/ledger.py build` writes `Ladruno_implementation/ledger/_build/{led}`\n"
        f"  (gitignored; CI uploads it as the `ledgers` artifact of the static-gates job).\n\n"
        f"<!-- ledger-stub kind={kind} split-source={source} -->\n"
    )


def stub_source(text: str) -> str | None:
    m = STUB_SOURCE_RE.search(text)
    return m.group(2) if m else None


# --------------------------------------------------------------------------
# git helpers
# --------------------------------------------------------------------------
def git(root: Path, *args: str, check: bool = True) -> str:
    r = subprocess.run(["git", "-C", str(root), *args], stdin=subprocess.DEVNULL,
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    if check and r.returncode != 0:
        raise LedgerError(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout


def git_show(root: Path, rev: str, path: str) -> str:
    return git(root, "show", f"{rev}:{path}").replace("\r\n", "\n")


def ledger_source(root: Path, kind: str, ref: str | None = None) -> tuple[str, str]:
    """(text of the full single-file ledger, where it came from). REF if given;
    else the working tree when it is still a full ledger; else the split source
    the stub records."""
    path = f"{IMPL_DIR}/{KINDS[kind]['ledger']}"
    if ref:
        return git_show(root, ref, path), ref
    p = root / path
    text = p.read_text(encoding="utf-8").replace("\r\n", "\n") if p.exists() else ""
    if text and STUB_MARK not in text:
        return text, "worktree"
    src = stub_source(text)
    if not src or src == "worktree":
        raise LedgerError(f"{path} is a stub without a git split source; pass --ref")
    return git_show(root, src, path), src


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------
def roundtrip(kind: str, text: str) -> list[str]:
    """Problems (empty = proof holds) with build(split(text)) vs text."""
    tpl, entries = parse_ledger(kind, text)
    frags = split_entries(kind, entries, set())
    # through the file format too: dump + parse every fragment
    frags = [Fragment(kind, f.name, *parse_fragment(f.text())) for f in frags]
    rebuilt = render(kind, tpl, frags)
    tpl2, entries2 = parse_ledger(kind, rebuilt)
    problems = []
    if tpl2 != tpl:
        diff = "\n".join(difflib.unified_diff(tpl.split("\n"), tpl2.split("\n"), lineterm="", n=1))
        problems.append(f"{kind}: template differs after the round trip:\n{diff[:2000]}")
    a = Counter((e.section, e.text) for e in entries)
    b = Counter((e.section, e.text) for e in entries2)
    for (sec, t), k in (a - b).items():
        problems.append(f"{kind}: entry lost ({sec}, x{k}): {t[:120]!r}")
    for (sec, t), k in (b - a).items():
        problems.append(f"{kind}: entry gained ({sec}, x{k}): {t[:120]!r}")
    return problems


def cmd_split(root: Path, ref: str | None) -> int:
    source = ref or "worktree"
    if not ref:
        try:
            dirty = git(root, "status", "--porcelain", "--", *(f"{IMPL_DIR}/{s['ledger']}" for s in KINDS.values()))
            source = "worktree" if dirty.strip() else git(root, "rev-parse", "HEAD").strip()
        except (LedgerError, OSError):
            source = "worktree"
    texts = {}
    for kind, spec in KINDS.items():           # validate all three before writing anything
        path = root / IMPL_DIR / spec["ledger"]
        text = git_show(root, ref, f"{IMPL_DIR}/{spec['ledger']}") if ref else path.read_text(encoding="utf-8")
        if STUB_MARK in text:
            raise LedgerError(f"{spec['ledger']} is already a stub -- the split has been done. "
                              "To capture rows added since, use `migrate`.")
        problems = roundtrip(kind, text)
        if problems:
            raise LedgerError("round trip fails, nothing written:\n" + "\n".join(problems))
        texts[kind] = text
    for kind, spec in KINDS.items():
        path = root / IMPL_DIR / spec["ledger"]
        tpl, entries = parse_ledger(kind, texts[kind])
        d = frag_dir(root, kind)
        d.mkdir(parents=True, exist_ok=True)
        kept = []
        for f in load_fragments(root, kind):
            if f.legacy:
                f.path.unlink()             # a previous split's output: regenerate it
            else:
                kept.append(f)
        taken = {f.name.lower() for f in kept}
        frags = split_entries(kind, entries, taken)
        (d / TEMPLATE).write_text(tpl, encoding="utf-8", newline="\n")
        for f in frags:
            (d / f"{f.name}.md").write_text(f.text(), encoding="utf-8", newline="\n")
        path.write_text(render_stub(kind, source), encoding="utf-8", newline="\n")
        print(f"split {spec['ledger']}: {len(entries)} entries -> {len(frags)} fragments "
              f"(+{len(kept)} kept) in {d.relative_to(root).as_posix()}/")
    print(f"split source: {source}")
    return 0


def _identity(kind: str, e: Entry) -> str:
    if kind == "quirks":
        return e.text.split("\n", 1)[0].strip()
    c = cells(e.text) if is_row(e.text) else [e.text[:80]]
    if kind == "vanilla":
        return f"{e.section}|{' '.join(c[0].split()) if c else ''}|{' '.join(c[-1].split()) if c else ''}"
    return f"{e.section}|{plain(c[0])[:100] if c else ''}"


def plan_migration(kind: str, base_text: str, head_text: str, frags: list[Fragment],
                   wp: str, date: str, taken: set[str]):
    """-> (new fragments, [(fragment, new body)], [messages for a human])."""
    _, base = parse_ledger(kind, base_text)
    tpl_head, head = parse_ledger(kind, head_text)
    tpl_base, _ = parse_ledger(kind, base_text)
    notes = []
    if tpl_head != tpl_base:
        notes.append(f"{kind}: the intro/conventions text changed; edit ledger/{kind}/_template.md by hand")
    a = Counter((e.section, e.text) for e in base)
    b = Counter((e.section, e.text) for e in head)
    removed = [Entry(s, t) for (s, t), k in (a - b).items() for _ in range(k)]
    added = [Entry(s, t) for (s, t), k in (b - a).items() for _ in range(k)]
    edits, new_entries = [], []
    for e in added:
        same = [r for r in removed if r.section == e.section and _identity(kind, r) == _identity(kind, e)]
        if not same:
            scored = sorted(((difflib.SequenceMatcher(None, r.text, e.text).quick_ratio(), i)
                             for i, r in enumerate(removed) if r.section == e.section), reverse=True)
            scored = [(s, i) for s, i in scored if s >= 0.6 and
                      difflib.SequenceMatcher(None, removed[i].text, e.text).ratio() >= 0.6]
            same = [removed[scored[0][1]]] if scored else []
        if not same:
            new_entries.append(e)
            continue
        old = same[0]
        removed.remove(old)
        owner = next((f for f in frags if old.text in f.body.split("\n") or f.body == old.text), None)
        if owner is None:
            notes.append(f"{kind}: an edited entry has no fragment holding its old text; add by hand: {e.text[:120]!r}")
            continue
        if kind == "vanilla":
            body = "\n".join(e.text if r == old.text else r for r in owner.body.split("\n"))
        else:
            body = e.text
        edits.append((owner, body))
    for r in removed:
        notes.append(f"{kind}: an entry was DELETED on the branch; delete or retract its fragment by hand: {r.text[:120]!r}")
    new: list[Fragment] = []
    if kind == "vanilla":
        by_table: dict[str, list[str]] = {}
        for e in new_entries:
            by_table.setdefault(e.section, []).append(e.text)
        for table, rows in by_table.items():
            pr_cells = {" ".join(cells(r)[-1].split()) for r in rows if cells(r)}
            meta = {"wp": wp, "title": f"{wp} vanilla rows" + ("" if table == "main" else " (upstreamable)"),
                    "date": date, "files": [cells(r)[0] for r in rows], "table": table}
            prs = sorted({int(x) for c in pr_cells for x in PR_IN.findall(c)})
            if prs:
                meta["pr"] = ", ".join(f"#{p}" for p in prs)
            name = _unique(f"{wp}-vanilla" + ("" if table == "main" else "-upstreamable"), taken)
            new.append(Fragment(kind, name, meta, "\n".join(rows)))
    else:
        for e in new_entries:
            meta = impl_meta(e.text, e.section if e.section == "history" else "table") \
                if kind == "implementations" else quirk_meta(e.text)
            meta["wp"] = wp
            meta["date"] = date
            if kind == "implementations" and e.section != "history":
                meta.setdefault("status", "draft")
            new.append(Fragment(kind, _name(wp, meta["title"], taken), meta, e.text))
    return new, edits, notes


def _branch_wp(root: Path) -> str | None:
    try:
        br = git(root, "rev-parse", "--abbrev-ref", "HEAD").strip()
    except LedgerError:
        return None
    m = re.match(r"^wp/(\d{1,4}[a-z]?)-", br)
    return f"WP-{m.group(1)}" if m else None


def cmd_migrate(root: Path, base: str, head: str, wp: str | None, dry: bool) -> int:
    wp = wp or _branch_wp(root)
    if not wp or not KEY_RE.match(wp):
        raise LedgerError("cannot tell the WP key; pass --wp WP-<n>")
    date = _dt.date.today().isoformat()
    any_change = False
    for kind, spec in KINDS.items():
        path = f"{IMPL_DIR}/{spec['ledger']}"
        base_text = git_show(root, base, path)
        head_text = git_show(root, head, path)
        if STUB_MARK in head_text:
            print(f"{spec['ledger']}: already a stub at {head} -- nothing to migrate")
            continue
        frags = load_fragments(root, kind)
        taken = {f.name.lower() for f in frags}
        new, edits, notes = plan_migration(kind, base_text, head_text, frags, wp, date, taken)
        for f in new:
            any_change = True
            p = frag_dir(root, kind) / f"{f.name}.md"
            print(f"{'would write' if dry else 'write'} {p.relative_to(root).as_posix()}")
            if not dry:
                p.write_text(f.text(), encoding="utf-8", newline="\n")
        for f, body in edits:
            any_change = True
            print(f"{'would edit' if dry else 'edit'} {f.path.relative_to(root).as_posix()}")
            if not dry:
                f.path.write_text(dump_fragment(f.meta, body), encoding="utf-8", newline="\n")
        for n in notes:
            print("MANUAL " + n)
    if not any_change:
        print("migrate: no ledger entries added or edited between the two revisions")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Per-WP ledger fragments (WP-161).")
    ap.add_argument("--root", type=Path, default=ROOT)
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build", help="render LEDGER_*.md into ledger/_build/")
    b.add_argument("--out", type=Path)
    s = sub.add_parser("split", help="one-time migration of the single-file ledgers")
    s.add_argument("--ref", help="split the ledgers at this revision instead of the working tree")
    m = sub.add_parser("migrate", help="turn a branch's single-file ledger edits into fragments")
    m.add_argument("--from-diff", required=True, metavar="BASE", help="the revision the branch forked from")
    m.add_argument("--head", default="HEAD")
    m.add_argument("--wp", help="WP key for new fragments (default: from the wp/<n>-... branch name)")
    m.add_argument("--dry-run", action="store_true")
    r = sub.add_parser("roundtrip", help="prove build(split(ledgers)) == ledgers")
    r.add_argument("--ref")
    args = ap.parse_args(argv)
    root = args.root.resolve()
    try:
        if args.cmd == "build":
            for kind, p in build(root, args.out).items():
                print(f"built {p.relative_to(root).as_posix() if p.is_relative_to(root) else p} "
                      f"({len(load_fragments(root, kind))} fragments)")
            return 0
        if args.cmd == "split":
            return cmd_split(root, args.ref)
        if args.cmd == "migrate":
            return cmd_migrate(root, args.from_diff, args.head, args.wp, args.dry_run)
        if args.cmd == "roundtrip":
            bad = []
            for kind in KINDS:
                text, src = ledger_source(root, kind, args.ref)
                probs = roundtrip(kind, text)
                print(f"roundtrip {kind} ({src}): {'OK' if not probs else 'FAIL'}")
                bad += probs
            for p in bad:
                print(p)
            return 1 if bad else 0
    except LedgerError as e:
        print(f"ledger: ERROR {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
