"""The harness's own gate (task item 5): parameter recovery on an O2-generated synthetic set.

Pipeline exercised end to end: energy plug (BA06) -> O2 drivers -> CSV schema writer -> loader -> objective ->
constrained multi-start least_squares -> identifiability (Jacobian condition + profiles of chi and h).
Synthetic set: drained PS at the two Tatsuoka 1986 states (sigma3' 49.0 kPa, e 0.716, Fig. 16a; sigma3' 4.9 kPa,
e 0.714, PSL-24 Fig. 4a; data/tatsuoka1986/source/compare.md), generated by O2 with THETA_TRUE and the Toyoura
PLACEHOLDER CSL (sand.py), sampled every 0.1 % axial strain (eps_v blank on alternate rows, to exercise the
schema), peak targets from the model curve itself. No noise: the truth is a zero-residual point.
Gate: max_j |theta_j - theta_true_j| / |theta_true_j| <= RECOVERY_TOL for each configuration run:
  'six'   all of (chi, h, N, N_bar, rho, rho_bar) free
  'rho_pinned'  rho fixed at its true value (the plan's P3 route: rho pinned from PS-vs-TC), five free
Run (compute node; see run_smoke.sbatch):  python -m harness.smoke_recovery [--starts 8] [--workers 8]
    [--configs six,rho_pinned] [--no-profiles]
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import numpy as np

from . import data as DATA
from . import fit as FIT
from .drivers import simulate
from .model import Setup, FIT_NAMES
from .objective import Objective, Weights, model_peak
from .sand import TOYOURA_PLACEHOLDER as TOY, phi_ps

THETA_TRUE = dict(chi=-3.0, h=150.0, N=0.3, N_bar=0.2, rho=0.712, rho_bar=0.75)
STATES = (("syn_PS_s49_e0716", 49.0, 0.716), ("syn_PS_s4.9_e0714", 4.9, 0.714))
RECOVERY_TOL = 1e-3
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "out"))


def make_synthetic(setup, W: Weights, outdir: str):
    paths = []
    os.makedirs(outdir, exist_ok=True)
    for name, s3, e in STATES:
        n_long = int(round(10.0 / W.deps_pct))
        c = simulate(setup, THETA_TRUE, "PS", s3, e, n_long * W.deps_pct / 100.0, n_long)
        if not c.complete:
            raise RuntimeError(f"synthetic {name}: O2 driver {c.status}")
        x = np.abs(c.eps_a_pct)
        srp, xp, interior = model_peak(x, c.sr)
        if not interior:
            raise RuntimeError(f"synthetic {name}: no interior peak within 10 %")
        x_end = xp + W.post_peak_pct
        keep = [k for k in range(0, len(x), 2) if x[k] <= x_end]
        ev = [c.eps_v_pct[k] if (j % 2 == 0) else float("nan") for j, k in enumerate(keep)]
        meta = dict(id=name, kind="PS", sigma3_kPa=s3, e0=e,
                    source=f"SYNTHETIC: O2 PS driver, THETA_TRUE {THETA_TRUE}, sand '{TOY.name}', "
                           f"energy BA06 per_test, {time.strftime('%Y-%m-%d')}",
                    phi_peak_deg=phi_ps(srp), eps_peak_pct=xp)
        p = os.path.join(outdir, name + ".csv")
        DATA.write_curve(p, meta, x[keep], c.sr[keep], ev)
        paths.append(p)
    return paths


def map_check(n=2000, seed=1):
    """Every u in [0,1]^k decodes to a set the owner's refusal rules accept (fit.check_admissible) and O2's
    Params.validate() accepts, for the free/fixed configurations the harness uses."""
    from .model import make_params
    rng = np.random.default_rng(seed)
    specs = [FIT.FitSpec(), FIT.FitSpec(free=("chi", "h", "N", "N_bar", "rho_bar"), fixed=dict(rho=0.712)),
             FIT.FitSpec(free=("chi", "h", "N", "N_bar"), fixed=dict(rho=0.712, rho_bar=0.75)),
             FIT.FitSpec(free=("chi", "h", "N", "rho_bar", "rho"), fixed=dict(N_bar=0.2))]
    setup = Setup(TOY)
    for sp in specs:
        for u in rng.random((n, len(sp.free))):
            th = sp.decode(u)
            assert FIT.check_admissible(th), (sp.free, u, th)
            make_params("O2", setup, th, 49.0, 0.716)
    return n


def recovery_error(theta, names):
    return {n: abs(theta[n] - THETA_TRUE[n]) / abs(THETA_TRUE[n]) for n in names}


def run(starts=8, workers=8, configs=("six", "rho_pinned"), profiles=True, seed=0, tag="", max_nfev=60,
        profile_factors=(0.95, 1.05), profile_nfev=15):
    t_all = time.perf_counter()
    sfx = f"_{tag}" if tag else ""
    progress = os.path.join(OUT, f"smoke_progress{sfx}.log")
    ls_kw = dict(max_nfev=max_nfev)
    setup = Setup(TOY)                     # BA06, per_test, WW, smooth cap, pi0 rule 'ramp_end' (model.Setup)
    n_map = map_check()
    print(f"constraint map: {n_map} random u per configuration decode to admissible sets accepted by O2 validate()")
    W = Weights()
    syn_dir = os.path.join(OUT, "synthetic")
    paths = make_synthetic(setup, W, syn_dir)
    curves = [DATA.load_curve(p) for p in paths]
    obj = Objective(setup, curves, weights=W)
    t0 = time.perf_counter()
    r_true = obj.residuals(THETA_TRUE)
    t_eval = time.perf_counter() - t0
    report = dict(date=time.strftime("%Y-%m-%d %H:%M:%S"), host=os.uname().nodename if hasattr(os, "uname") else "",
                  theta_true=THETA_TRUE, sand=TOY.as_dict(), weights=W.as_dict(), energy="BA06",
                  synthetic=[os.path.relpath(p, OUT) for p in paths], n_residuals=int(r_true.size),
                  residual_norm_at_truth=float(np.linalg.norm(r_true)), seconds_per_residual_eval=t_eval,
                  starts=starts, workers=workers, configs={})
    print(f"synthetic written: {paths}; n_res {r_true.size}; |r(truth)| {np.linalg.norm(r_true):.3e}; "
          f"one residual eval {t_eval:.2f} s")
    sys.stdout.flush()
    all_ok = True
    for cfg in configs:
        if cfg == "six":
            spec = FIT.FitSpec(free=FIT_NAMES, fixed={})
        elif cfg == "rho_pinned":
            spec = FIT.FitSpec(free=tuple(n for n in FIT_NAMES if n != "rho"), fixed=dict(rho=THETA_TRUE["rho"]))
        else:
            raise ValueError(cfg)
        u_true = spec.encode(THETA_TRUE)
        assert np.all((u_true > 0) & (u_true < 1)), f"truth not interior in u: {u_true}"
        rt = spec.decode(u_true)
        assert all(abs(rt[n] - THETA_TRUE[n]) <= 1e-12 * abs(THETA_TRUE[n]) for n in FIT_NAMES), (rt, THETA_TRUE)
        t0 = time.perf_counter()
        with open(progress, "a") as f:
            f.write(f"{time.strftime('%H:%M:%S')} config {cfg}: {starts} starts, {workers} workers\n")
        runs = FIT.multistart(obj, spec, n_starts=starts, seed=seed, workers=workers, ls_kw=ls_kw, progress=progress)
        t_fit = time.perf_counter() - t0
        best = runs[0]
        assert FIT.check_admissible(best["theta"])
        err = recovery_error(best["theta"], spec.free)
        n_rec = sum(1 for r in runs if max(recovery_error(r["theta"], spec.free).values()) <= RECOVERY_TOL)
        ok = max(err.values()) <= RECOVERY_TOL
        all_ok = all_ok and ok
        print(f"[{cfg}] {len(runs)} starts, {t_fit:.0f} s wall; best cost {best['cost']:.3e}; "
              f"recovered by {n_rec}/{len(runs)} starts; max rel err {max(err.values()):.2e} -> {'PASS' if ok else 'FAIL'}")
        for n in spec.free:
            print(f"    {n:8s} true {THETA_TRUE[n]: .6g}  fit {best['theta'][n]: .8g}  rel {err[n]:.2e}")
        for r in runs:
            e = max(recovery_error(r["theta"], spec.free).values())
            print(f"    start {r['start']:2d}: cost {r['cost']:.3e}  max rel err {e:.2e}  nfev {r['nfev']:4d}  "
                  f"{r['seconds']:.0f} s  status {r['status']}")
        sys.stdout.flush()
        t0 = time.perf_counter()
        ident = FIT.identifiability(obj, best["theta"], spec.free)
        t_id = time.perf_counter() - t0
        print(f"    Jacobian (d r / d ln theta) singular values {np.array(ident['singular_values'])}; "
              f"condition {ident['condition']:.3e} ({t_id:.0f} s)")
        print(f"    weakest direction {ident['weakest_direction']}")
        rec = dict(free=list(spec.free), fixed=spec.fixed, runs=runs, best=best, rel_err=err,
                   n_starts_recovered=n_rec, ok=ok, fit_wall_seconds=t_fit, identifiability=ident)
        if profiles:
            prof = {}
            for nm in ("chi", "h"):
                t0 = time.perf_counter()
                pr = FIT.profile(obj, spec, best["theta"], nm, factors=profile_factors,
                                 workers=workers, ls_kw=dict(max_nfev=profile_nfev), progress=progress)
                prof[nm] = dict(points=pr, wall_seconds=time.perf_counter() - t0, max_nfev=profile_nfev,
                                note="cost after at most max_nfev TRF iterations: an upper bound of the profile")
                print(f"    profile {nm}: " + "  ".join(
                    f"x{p['factor']}: {p['cost']:.3e}" if p.get("cost") is not None else f"x{p['factor']}: -"
                    for p in pr) + f"   ({prof[nm]['wall_seconds']:.0f} s)")
                sys.stdout.flush()
            rec["profiles"] = prof
        report["configs"][cfg] = rec
    report["wall_seconds"] = time.perf_counter() - t_all
    report["gate"] = "PASS" if all_ok else "FAIL"
    os.makedirs(OUT, exist_ok=True)
    report["max_nfev"] = max_nfev
    with open(os.path.join(OUT, f"smoke_recovery{sfx}.json"), "w") as f:
        json.dump(report, f, indent=1, default=str)
    print(f"SMOKE {report['gate']}  total wall {report['wall_seconds']:.0f} s")
    return all_ok


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--starts", type=int, default=8)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--configs", default="six,rho_pinned")
    ap.add_argument("--no-profiles", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--tag", default="")
    ap.add_argument("--max-nfev", type=int, default=60)
    ap.add_argument("--profile-factors", default="0.95,1.05")
    ap.add_argument("--profile-nfev", type=int, default=15)
    a = ap.parse_args()
    ok = run(a.starts, a.workers, tuple(a.configs.split(",")), not a.no_profiles, a.seed, a.tag, a.max_nfev,
             tuple(float(x) for x in a.profile_factors.split(",")), a.profile_nfev)
    sys.exit(0 if ok else 1)
